In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [5]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
## preprocess the data
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [7]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [8]:
## onehot encode
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [9]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [10]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [11]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [12]:
##combine columns
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [13]:
# save the encoder and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [14]:
X=data.drop('Exited',axis=1)
y=data['Exited']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [15]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

ANN Implementation

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [17]:
## build ANN Model
model =Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
]

)

WARNING:tensorflow:From c:\Users\ASUS\OneDrive\Desktop\ai-udemy\prj 1 ann project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [20]:
## compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [37]:
##setup tensor board
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/"+ datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [38]:
## set up early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [25]:
## train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\ASUS\OneDrive\Desktop\ai-udemy\prj 1 ann project\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\ASUS\OneDrive\Desktop\ai-udemy\prj 1 ann project\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 6ms/step - loss: 0.4014 - accuracy: 0.8310 - val_loss: 0.3648 - val_accuracy: 0.8565
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3583 - accuracy: 0.8539 - val_loss: 0.3629 - val_accuracy: 0.8545
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3474 - accuracy: 0.8586 - val_loss: 0.3592 - val_accuracy: 0.8605
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3487 - accuracy: 0.8559 - val_loss: 0.3667 - val_accuracy: 0.8540
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3425 - accuracy: 0.8620 - val_loss: 0.3523 - val_accuracy: 0.8545
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3438 - accuracy: 0.8590 - val_loss: 0.3478 - val_accuracy: 0.8600
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3370 - accuracy: 0.8637 - val_loss: 0.3513 - val_accuracy: 0.8555
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8612 - val_loss: 0.3550 - val_accuracy: 0.8570
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3343 - accuracy: 0.8630 - val_loss: 0.3475 - val_accuracy: 0.8570
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3316 - accuracy: 0.8674 - val_loss: 0.3617 - val_accuracy: 0.8590
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3273 - accuracy: 0.8671 - val_loss: 0.3497 - val_accuracy: 0.8555
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3282 - accuracy: 0.8652 - val_loss: 0.3526 - val_accuracy: 0.8575
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3251 - accuracy: 0.8666 - val_loss: 0.3482 - val_accuracy: 0.8540
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3228 - accuracy: 0.8695 - val_loss: 0.3468 - val_accuracy: 0.8625
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3183 - accuracy: 0.8674 - val_loss: 0.3527 - val_accuracy: 0.8585
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3186 - accuracy: 0.8716 - val_loss: 0.3560 - val_accuracy: 0.8570
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3150 - accuracy: 0.8723 - val_loss: 0.3571 - val_accuracy: 0.8550
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3143 - accuracy: 0.8721 - val_loss: 0.3595 - val_accuracy: 0.8540
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3147 - accuracy: 0.8748 - val_loss: 0.3568 - val_accuracy: 0.8555

In [26]:
model.save('model.h5')

c:\Users\ASUS\OneDrive\Desktop\ai-udemy\prj 1 ann project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [29]:
## load tensoroard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [ ]:
%tensorboard --logdir logs/fit20260812-120840

Reusing TensorBoard on port 6007 (pid 19384), started 0:00:49 ago. (Use '!kill 19384' to kill it.)

c:\Users\ASUS\OneDrive\Desktop\ai-udemy\prj 1 ann project\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 13 columns]

KeyError: "['Geography'] not found in axis"

In [51]:
#scaling the data
input_scaled=scaler.transform(input_df)
input_scaled

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- gender